name: Python FastAPI CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest uvicorn fastapi

      # Step 4: Lint with flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Step 5: Run tests with pytest
      - name: Test with pytest
        run: pytest

      # Step 6: Run the app locally (optional, for testing only)
      - name: Run app locally
        run: |
          echo "Starting FastAPI app with uvicorn..."
          uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload & sleep 5
          ps aux | grep uvicorn

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          echo "Starting Deployment..."
          # Replace with actual deployment, for example:
          # ssh user@server "cd /path/to/project && git pull && systemctl restart my-service"
